#pragma once

#include <Arduino.h>

// Feature toggles
#define ENABLE_LIGHTS 1
#define ENABLE_WHEEL_HALL 1
#define ENABLE_BOARD_OLED 1
#define ENABLE_REMOTE_OLED 1
#define ENABLE_VESC_UART 1
#define ENABLE_CRUISE 1
#define ENABLE_BINDING 1
#define ENABLE_REMOTE_PERSISTENCE 1
#define ENABLE_BOARD_PERSISTENCE 1

// Radio settings
static const uint8_t RADIO_ADDRESS[5] = {'E', 'S', 'K', '8', '1'};
static const uint8_t RADIO_BIND_ADDRESS[5] = {'B', 'I', 'N', 'D', '0'};
#define RADIO_CHANNEL 90
#define RADIO_BIND_CHANNEL RADIO_CHANNEL
#define RADIO_DATA_RATE RF24_1MBPS
#define RADIO_PA_LEVEL RF24_PA_MAX
#define RADIO_RETRY_DELAY 5
#define RADIO_RETRY_COUNT 5
#define RADIO_FAILSAFE_MS 400
#define RADIO_SEND_INTERVAL_MS 50
#define RADIO_BIND_RETRY_MS 200

// Remote (Arduino Nano) pins and parameters
#define REMOTE_RF24_CE_PIN 9
#define REMOTE_RF24_CSN_PIN 10
#define REMOTE_TRIGGER_PIN 4
#define REMOTE_HALL_PIN A0
#define REMOTE_BATTERY_PIN A1
#define REMOTE_ADC_REF_V 5.0f
#define REMOTE_BATTERY_DIVIDER 2.0f
#define REMOTE_BATTERY_CELL_COUNT 1
#define REMOTE_CELL_MIN_V 3.2f
#define REMOTE_CELL_MAX_V 4.2f
#define REMOTE_HALL_MIN 120
#define REMOTE_HALL_CENTER 512
#define REMOTE_HALL_MAX 900
#define REMOTE_HALL_SAMPLES 8
#define REMOTE_HALL_DEADZONE 25
#define REMOTE_THROTTLE_MAX_PERCENT 100
#define REMOTE_BRAKE_MAX_PERCENT 100
#define REMOTE_ACCEL_TIME_S 0
#define REMOTE_BRAKE_TIME_S 0
#define REMOTE_CRUISE_TIME_S 1
#define REMOTE_RANGE_KM_DEFAULT 20
#define REMOTE_RANGE_KM_MAX 99
#define REMOTE_TRIGGER_ACTIVE_LOW 1
#define REMOTE_UI_SHORT_PRESS_MS 400
#define REMOTE_UI_LONG_PRESS_MS 900
#define REMOTE_UI_NEUTRAL_MARGIN 80
#define REMOTE_UI_NAV_MARGIN 140
#define REMOTE_UI_REFRESH_MS 100
#define REMOTE_SETTINGS_SAVE_MS 1500
#define REMOTE_SETTINGS_VERSION 2

// Board (ESP32 NodeMCU) pins and parameters
#define BOARD_RF24_CE_PIN 27
#define BOARD_RF24_CSN_PIN 5
#define BOARD_SPI_SCK 18
#define BOARD_SPI_MISO 19
#define BOARD_SPI_MOSI 23
#define BOARD_VESC_UART_RX 16
#define BOARD_VESC_UART_TX 17
#define BOARD_OLED_SDA 21
#define BOARD_OLED_SCL 22
#define BOARD_OLED_ADDR 0x3C

#define BOARD_WHEEL_HALL_PIN 34
#define BOARD_WHEEL_HALL_PULLUP 0
#define BOARD_WHEEL_DIAMETER_MM 90.0f
#define BOARD_MAGNETS_PER_REV 1
#define BOARD_MOTOR_POLES 14
#define BOARD_GEAR_RATIO 2.6f

#define BOARD_BATTERY_CELL_COUNT 10
#define BOARD_CELL_MIN_V 3.2f
#define BOARD_CELL_MAX_V 4.2f

#define BOARD_CONTROL_INTERVAL_MS 10
#define BOARD_WHEEL_SPEED_INTERVAL_MS 200
#define BOARD_FAILSAFE_RAMP_STEP 40
#define BOARD_THROTTLE_DEADZONE 30
#define BOARD_MAX_CURRENT_A 35.0f
#define BOARD_MAX_BRAKE_CURRENT_A 20.0f
#define BOARD_BINDING_SAFE_SPEED_KPH 2.0f
#define BOARD_PERSIST_INTERVAL_MS 5000
#define BOARD_PERSIST_DISTANCE_M 5
#define BOARD_PERSIST_ENERGY_WH 1.0f

#define BOARD_CRUISE_MIN_KPH 6.0f
#define BOARD_CRUISE_KP 0.08f
#define BOARD_CRUISE_MAX_THROTTLE 0.6f
#define BOARD_BRAKE_CURRENT_ON_A -2.0f

#define BOARD_LIGHT_HEAD_PIN 25
#define BOARD_LIGHT_BRAKE_PIN 26
#define BOARD_DISPLAY_REFRESH_MS 200
